<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>AudioEngine.Example</AssemblyName>
    <RootNamespace>AudioEngine.Example</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AudioEngine.Core/AudioEngine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
